name: Jenkins Security Scan
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  security-scan:
    if: ${{ github.event_name != 'pull_request' || github.event.pull_request.base.repo.full_name == github.repository }}
    uses: jenkins-infra/jenkins-security-scan/.github/workflows/jenkins-security-scan.yaml@v1
    with:
      java-cache: '' # Optionally enable use of a build dependency cache. Specify 'maven' or 'gradle' as appropriate.
      java-version: 11 # What version of Java to set up for the build.
